services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["node", "server.js"]
    expose:
      - '80'
    env_file:
      - ./.env
    volumes:
      - .:/app:delegated
      - /app/node_modules
    networks:
      - apichatmii_sail
    restart: unless-stopped

networks:
  apichatmii_sail:
    external: true