services:
  websocket:
    build:
      context: .
    container_name: websocket-server
    expose:
      - '80'
    networks:
      - apichatmii_sail
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  apichatmii_sail:
    external: true
